apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.kuboard.cn/layer: svc
  name: blog-service
  namespace: syzero
spec:
  replicas: 3
  selector:
    matchLabels:
      project: blog
      app: service
  syzero.blog:
    metadata:
      labels:
        project: blog
        app: service
    spec:
      imagePullSecrets:
      - name: registry-pull-secret
      containers:
      - name: ssr
        image: $IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: web
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: syzero
  labels:
    project: blog
    app: service
spec:
  selector:
    project: blog
    app: service
  ports:
  - name: web
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30005
  type: NodePort

